name: 'Create New Hugo Post'

on:
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Title of the new blog post'
        required: true
      directory:
        description: 'Subdirectory within content/posts. Leave blank for root.'
        required: false
        default: ''

jobs:
  create_new_post:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          
      # 3. Create the new post
      - name: Create New Post
        run: |
          # Get the title from the workflow input
          POST_TITLE="${{ github.event.inputs.post_title }}"
          
          # Convert title to a URL-friendly "slug"
          FILENAME=$(echo "$POST_TITLE" | iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+\|-+$//g' | tr '[:upper:]' '[:lower:]')
          
          # Safely build the relative path for the new post
          BASE_PATH="content/posts"
          SUBDIR="${{ github.event.inputs.directory }}"
          
          # Check if a subdirectory was provided and construct the final path
          if [[ -n "$SUBDIR" ]]; then
            FINAL_PATH="$BASE_PATH/$SUBDIR/$FILENAME.md"
          else
            FINAL_PATH="$BASE_PATH/$FILENAME.md"
          fi
          
          echo "Attempting to create post at: $FINAL_PATH"
          hugo new --kind post "$FINAL_PATH"

      # 4. Commit and push the new file to the repository
      - name: Commit and Push New Post
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: create new post '${{ github.event.inputs.post_title }}' 📝" || echo "No changes to commit"
          git push